In [1]:
# datasetX, principle components U, the numbers of dimensions to reduce to k
import time
import numpy as np
# sklearn are prohibited
import os
#import sklearn
from scipy import misc
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.image as mpimg

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import fetch_lfw_people
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from PIL import Image
import random

from sklearn.cluster import KMeans

error load image

In [2]:
error_image_foldpath = []
error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/01/1605_Emp') 
error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/01/1611_Emp') 
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/01/1627_Emp') 
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/01/1658_Emp') 
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/01/1707_Emp') 
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/01/1717_Emp')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/01/1727_Emp') 
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/02/1157_Emp')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/02/1421_Emp')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/02/1431_Emp')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/02/1443_Emp')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/02/1658_Emp')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/02/19402CAE')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/03/1120_Emp')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/03/1125_Emp')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/03/1129_Emp')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/03/1432_Emp')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/03/1451_Emp')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/03/1509_Emp')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/08/1532_Emp')
error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/08/1541_Emp')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/08/190410AB')
# error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/1552_Emp')
error_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409IAP')
#path = 'PL/2019/05/08/' #jpg
#image= misc.imread(path + filenamelist[0], flatten= 0)

error_image_path = []
# r=root, d=directories, f = files
for path in error_image_foldpath:
    for r, d, f in os.walk(path):
        for file in f:
            if '.jpg' in file:
                error_image_path.append(os.path.join(r, file))

error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/4_A1M9NP0308.jpg')
error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/6_A1M9NP0309.jpg')
error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/8_A1M9NP0310.jpg')
error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/10_A1M9NP0311.jpg')
error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/12_A1M9NP0312.jpg')
error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/14_A1M9NP0307.jpg')
error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/16_A1M9NP0313.jpg')
error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/18_A1M9NP0314.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/20_A1M9NP0315.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/22_A1M9NP0324.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/24_A1M9NP0317.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/26_A1M9NP0318.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/28_A1M9NP0320.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/30_A1M9NP0321.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/32_A1M9NP0316.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/34_A1M9NP0332.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/36_A1M9NP0323.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/38_A1M9NP0319.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/40_A1M9NP0326.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/42_A1M9NP0327.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/44_A1M9NP0322.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/46_A1M9NP0329.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/48_A1M9NP0330.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/50_A1M9NP0325.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/40_A1M9NP0326.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/40_A1M9NP0326.jpg')
# error_image_path.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409EAP/40_A1M9NP0326.jpg')
len(error_image_path)

53

normal load image

In [3]:
normal_image_foldpath = []
normal_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409GBP')
normal_image_foldpath.append('/home/chang_1909004/Documents/Inline_PL/PL/2019/04/10/19409CAE')
normal_image_path = []
# r=root, d=directories, f = files
for path in normal_image_foldpath:
    for r, d, f in os.walk(path):
        for file in f:
            if '.jpg' in file:
                normal_image_path.append(os.path.join(r, file))
                
len(normal_image_path)

84

In [4]:
image_path = error_image_path + normal_image_path

In [5]:
len(image_path)

137

In [6]:
from multiprocessing import Pool

def read_image(path_index):
    image = mpimg.imread(image_path[path_index])
    return image.flatten()

p = Pool(processes=17)

png_imagelist = p.map(read_image, range(len(image_path)))
p.close()
p.join()

In [7]:
len(png_imagelist)

137

In [8]:
png_imagelist[0].shape

(12024030,)

In [16]:
for i in range(len(png_imagelist)):
    plt.imsave("/media/chang_1909004/970pro/PL/137whole_clustering_input/" + str(i) + ".jpg", png_imagelist[i].reshape(mpimg.imread(image_path[0]).shape), cmap='gray')

kmeans clustering

In [9]:
from sklearn.cluster import KMeans

In [28]:
kmeans = KMeans(n_clusters=4, random_state=0).fit(png_imagelist)
kmeans.labels_ 

array([2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 3, 3, 1, 3, 3, 1, 3, 1, 1, 3,
       3, 3, 1, 1, 1, 3, 1, 1, 3, 1, 1, 3, 1, 1, 1, 1, 3, 1, 3, 1, 3, 1,
       1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 1, 1, 3, 1, 1, 3, 1, 3, 3, 1,
       1, 3, 1, 3, 1, 3, 3, 1, 1, 3, 1, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 1,
       1, 3, 1, 1, 3], dtype=int32)

In [14]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(png_imagelist)
kmeans.labels_ 

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2,
       2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2,
       2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 2,
       2, 1, 2, 2, 1], dtype=int32)

In [17]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(png_imagelist)
kmeans.labels_ 

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0], dtype=int32)

from sklearn.cluster import AffinityPropagation

In [18]:
from sklearn.cluster import AffinityPropagation

clustering = AffinityPropagation().fit(png_imagelist)

clustering.labels_

array([0, 0, 0, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 4, 6, 6, 8, 3, 3, 3, 5, 6, 3, 4, 6, 8,
       3, 3, 4, 4, 6, 5, 4, 4, 3, 7, 6, 3, 6, 3, 6, 4, 3, 6, 5, 8, 5, 3,
       4, 6, 3, 8, 4, 6, 8, 5, 5, 5, 3, 5, 7, 7, 5, 7, 7, 5, 6, 5, 5, 7,
       6, 3, 6, 3, 7, 8, 8, 6, 7, 8, 7, 5, 8, 8, 8, 8, 5, 5, 8, 5, 5, 7,
       6, 5, 6, 8, 5])

MeanShift #memory error

In [19]:
# from sklearn.cluster import MeanShift

# clustering = MeanShift(bandwidth=2, n_jobs = -1).fit(png_imagelist)
# clustering.labels_

In [20]:
# from sklearn.cluster import MeanShift

# clustering = MeanShift(bandwidth=3, n_jobs = -1).fit(png_imagelist)
# clustering.labels_

SpectralClustering

In [21]:
from sklearn.cluster import SpectralClustering

clustering = SpectralClustering(n_clusters=2,
        assign_labels="discretize", n_jobs = -1,
        random_state=0).fit(png_imagelist)
clustering.labels_

/home/chang_1909004/anaconda3/lib/python3.7/site-packages/sklearn/manifold/spectral_embedding_.py:235: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn("Graph is not fully connected, spectral embedding"


array([1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1])

In [22]:
from sklearn.cluster import SpectralClustering

clustering = SpectralClustering(n_clusters=3,
        assign_labels="discretize", n_jobs = -1,
        random_state=0).fit(png_imagelist)
clustering.labels_

/home/chang_1909004/anaconda3/lib/python3.7/site-packages/sklearn/manifold/spectral_embedding_.py:235: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn("Graph is not fully connected, spectral embedding"


array([1, 0, 2, 0, 1, 2, 0, 2, 2, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 0, 1, 2,
       0, 2, 2, 0, 0, 1, 1, 0, 0, 2, 1, 1, 2, 0, 2, 1, 1, 1, 2, 0, 0, 1,
       0, 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 2, 1, 1, 0, 2, 1, 0,
       0, 2, 0, 0, 2, 0, 1, 0, 0, 2, 1, 0, 2, 2, 0, 2, 2, 1, 1, 0, 1, 2,
       1, 0, 0, 0, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 0, 2, 1, 1, 2, 1, 0, 2,
       0, 2, 0, 1, 1, 2, 2, 1, 2, 0, 2, 0, 2, 1, 0, 1, 2, 2, 2, 1, 2, 1,
       0, 2, 1, 1, 2])

AgglomerativeClustering

In [23]:
from sklearn.cluster import AgglomerativeClustering
import numpy as np

clustering = AgglomerativeClustering(n_clusters=2).fit(png_imagelist)

clustering.labels_

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [29]:
from sklearn.cluster import AgglomerativeClustering
import numpy as np

clustering = AgglomerativeClustering(n_clusters=3).fit(png_imagelist)

clustering.labels_

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2,
       2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2,
       2, 0, 2, 2, 0])

DBSCAN

In [24]:
from sklearn.cluster import DBSCAN

clustering = DBSCAN(eps=3, min_samples=2, n_jobs = -1).fit(png_imagelist)
clustering.labels_

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1])

OPTICS

In [25]:
from sklearn.cluster import OPTICS

clustering = OPTICS(min_samples=2, n_jobs = -1).fit(png_imagelist)
clustering.labels_

array([ 0,  0,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, 16, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, 15, -1, -1, -1, -1, -1, -1, 15, 16, 14, -1, 14, 14, 17, -1,
       -1, 17, 13, 12, 12, -1, -1, -1, -1, -1, 12, -1, 13, 12, -1, -1, -1,
       -1, 13, 12, -1, -1, -1, -1, 10, 12, -1, -1, -1, 12, 10, -1, -1, -1,
       -1, -1, -1, -1, 12, -1, -1, 13, 12, -1, -1,  3,  2, -1,  2,  7,  9,
       -1,  8,  7,  3, 11, -1,  3,  6, 11, -1, 11, -1,  6,  5,  4, -1,  9,
        5,  7,  3, -1,  6,  4, -1,  1, -1,  4, -1, -1, -1, 11,  1,  8, -1,
       -1])

Birch

In [26]:
from sklearn.cluster import Birch

brc = Birch(n_clusters=2)
brc.fit(png_imagelist)
brc.labels_

/home/chang_1909004/anaconda3/lib/python3.7/site-packages/sklearn/cluster/birch.py:299: RuntimeWarning: overflow encountered in ubyte_scalars
  new_ss = self.squared_sum_ + nominee_cluster.squared_sum_
/home/chang_1909004/anaconda3/lib/python3.7/site-packages/sklearn/cluster/birch.py:627: ConvergenceWarning: Number of subclusters found (1) by Birch is less than (2). Decrease the threshold.
  % (len(centroids), self.n_clusters), ConvergenceWarning)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [27]:
from sklearn.cluster import Birch

brc = Birch(n_clusters=3)
brc.fit(png_imagelist)
brc.labels_

/home/chang_1909004/anaconda3/lib/python3.7/site-packages/sklearn/cluster/birch.py:299: RuntimeWarning: overflow encountered in ubyte_scalars
  new_ss = self.squared_sum_ + nominee_cluster.squared_sum_
/home/chang_1909004/anaconda3/lib/python3.7/site-packages/sklearn/cluster/birch.py:627: ConvergenceWarning: Number of subclusters found (1) by Birch is less than (3). Decrease the threshold.
  % (len(centroids), self.n_clusters), ConvergenceWarning)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [55]:
kmeans.labels_[53]

0

In [46]:
len(png_imagelist)

137

In [49]:
png_imagelist[0].shape

(12024030,)

In [ ]:
for i in range(len(png_imagelist)):
    plt.imsave("/media/chang_1909004/970pro/PL/137whole_clustering_input/" + str(i) + ".jpg", png_imagelist[i].reshape(mpimg.imread(image_path[0]).shape), cmap='gray')

In [51]:
mpimg.imread(image_path[0]).shape

(2469, 4870)

In [ ]:
kmeans.labels_



In [ ]:
kmeans.predict([[0, 0], [12, 3]])



In [ ]:
kmeans.cluster_centers_